sudo: required

language: php
php:
  - '7.2'

services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - export GIT_COMMIT_SHA=$TRAVIS_COMMIT
  - export GIT_BRANCH=$TRAVIS_BRANCH
  - ./cc-test-reporter before-build
script:
  - composer install
  - composer ci
after_success:
  - ./cc-test-reporter after-build --exit-code 0 --debug

notifications:
  email: false
  slack:
    secure: EgfrI8YpMSl4iNGmfluIrPDNG2lRS2p+w3c4AqOFnjRv9auKl6aBmeE0sQ0E3vBEdAOmsjNC+jqoRozjR+EtSx19k0SLVkFEIueuZJUOoHurQjXPSyw67ZgY3iTPlMCV9/QLY2njXr+oeMjdwGLDWf+JL2K59c5UVOBGa43n8gMdT2sewNw1NEwiXdOuYasckkXOyI/+Upjg/mHl8vDs2Nlya6CePdNf1iAxerlcXLER5Y8gSLORou0l0zc4jePX/25Gb8jUpbYCYqpXG4X0ydOKGhZT6KQwwcRsjmTbZE7DK3P43jB0Ah7p0cIeLJCYjIX2Jqj5M+ga6sK4TXR8EvCzVVyyjayptY8bGq487C5lNxY+WPOXfPcQPfl2gttNeFZWwRH2cTKaHhZXK1Gxkqd69+tqoIlQ7acqGyDw3uugiNtjxsYdkMr71Ez/dI1ftk609rEVPUmb4iY+MO2+yIy7nCi4YaIHuM6pxOEGZEMYhGzk1CdnrZXaaTw/hoipi95F5m9rpy2vf9MOLXomNFmMLvo49e9uUmNlVXKhmvJorN8ZMpXpz/uibo6F+TPZ7ixxMOD6RTUbulNsmYyIHAeCO9oWp4JbZRP2CigqBg9+25xmhCBhiBkmJ7KvfXEU+Wil414MT4OfSmYNDmPDIf3vrTC+6LdIXtc+XDYETiw=
