version: "3.4"
services:
  dev:
    build:
      context: .
      target: dev
      args:
        PHP_VERSION: 8.0
    volumes:
      - ./:/code
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
      - ABS_CONNECTION_STRING
      - ABS_CONTAINER
      - S3_LOGS_BUCKET
