version: "2"
services:
  # for development purposes
  dev:
    build: .
    volumes:
        - ./:/code
    environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
        - ABS_CONNECTION_STRING
        - ABS_CONTAINER
        - S3_LOGS_BUCKET
